name: Ingestion CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  debug: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # , "macos-latest", "windows-latest"
        python-version: ["3.9"]

    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: pipeline_env
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Conda info
        if: env.debug == 'true'
        shell: bash -l {0}
        run: conda info

      - name: Conda list
        if: env.debug == 'true'
        shell: bash -l {0}
        run: conda list

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/
